"""Unit tests for ``scripts/stats/check_repro.py`` (D-011 Invariant 2, T-064).

These are pure tests over tiny synthetic trees. They exercise the wrapper's
comparison, manual spot-check pre-seed, results-tree dirt guard, and end-to-end
orchestration via an **injected fake regenerator** — they never run the real
bootstrap (the live byte-for-byte run is the `python scripts/stats/check_repro.py`
validation command, not a unit test).
"""

from __future__ import annotations

import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from scripts.stats import check_repro as cr  # noqa: E402
from scripts.stats import inter_rater as ir  # noqa: E402

ARTIFACTS = cr.ARTIFACTS


def _write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _seed_committed(root: pathlib.Path, benchmarks, payload="{}\n") -> None:
    for b in benchmarks:
        for name in ARTIFACTS:
            _write(root / b / name, payload)


# ----------------------------------------------------------------------------
# compare_artifacts
# ----------------------------------------------------------------------------


def test_compare_all_match(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    committed = tmp_path / "committed"
    regen = tmp_path / "regen"
    _seed_committed(committed, benchmarks, payload='{"a":1}\n')
    _seed_committed(regen, benchmarks, payload='{"a":1}\n')

    results = cr.compare_artifacts(
        benchmarks, ARTIFACTS, committed_dir=committed, regenerated_dir=regen
    )
    assert len(results) == len(ARTIFACTS)
    assert all(r.ok for r in results)
    assert {r.status for r in results} == {"match"}


def test_compare_detects_perturbed_artifact(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    committed = tmp_path / "committed"
    regen = tmp_path / "regen"
    _seed_committed(committed, benchmarks, payload='{"a":1}\n')
    _seed_committed(regen, benchmarks, payload='{"a":1}\n')
    # Perturb a single regenerated byte.
    _write(regen / "01-short-factual" / "cohens_d.json", '{"a":2}\n')

    results = cr.compare_artifacts(
        benchmarks, ARTIFACTS, committed_dir=committed, regenerated_dir=regen
    )
    differing = [r for r in results if not r.ok]
    assert len(differing) == 1
    assert differing[0].artifact == "cohens_d.json"
    assert differing[0].status == "differ"


def test_compare_flags_missing_files(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    committed = tmp_path / "committed"
    regen = tmp_path / "regen"
    _write(committed / "01-short-factual" / "bootstrap_ci.json", "{}\n")
    _write(regen / "01-short-factual" / "cohens_d.json", "{}\n")

    results = cr.compare_artifacts(
        benchmarks, ARTIFACTS, committed_dir=committed, regenerated_dir=regen
    )
    by_name = {r.artifact: r.status for r in results}
    assert by_name["bootstrap_ci.json"] == "missing_regenerated"
    assert by_name["cohens_d.json"] == "missing_committed"
    assert by_name["inter_rater.json"] == "missing_committed"


# ----------------------------------------------------------------------------
# preseed_manual_spot_checks
# ----------------------------------------------------------------------------


def test_preseed_copies_committed_manual_scores(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual", "02-multi-step-reasoning")
    results_dir = tmp_path / "results"
    out_dir = tmp_path / "tmp"
    _write(
        results_dir / "01-short-factual" / cr.MANUAL_SPOT_CHECKS,
        '{"scores":[]}\n',
    )

    seeded = cr.preseed_manual_spot_checks(
        benchmarks, results_dir=results_dir, output_dir=out_dir
    )
    assert seeded == ["01-short-factual"]
    copied = out_dir / "01-short-factual" / cr.MANUAL_SPOT_CHECKS
    assert copied.read_text(encoding="utf-8") == '{"scores":[]}\n'
    # No manual scores for benchmark 02 -> nothing created.
    assert not (out_dir / "02-multi-step-reasoning" / cr.MANUAL_SPOT_CHECKS).exists()


def test_preseed_noop_when_absent(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    seeded = cr.preseed_manual_spot_checks(
        benchmarks,
        results_dir=tmp_path / "results",
        output_dir=tmp_path / "tmp",
    )
    assert seeded == []


# ----------------------------------------------------------------------------
# check_repro end-to-end with an injected fake regenerator
# ----------------------------------------------------------------------------


def test_check_repro_match_with_fake_regenerator(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    results_dir = tmp_path / "results"
    _seed_committed(results_dir, benchmarks, payload='{"ok":true}\n')

    seen: dict[str, object] = {}

    def fake_regenerate(bms, *, benchmarks_dir, pricing_dir, output_dir):
        seen["benchmarks_dir"] = benchmarks_dir
        seen["pricing_dir"] = pricing_dir
        # Faithful regenerator: reproduce the committed bytes exactly.
        _seed_committed(output_dir, bms, payload='{"ok":true}\n')

    outcome = cr.check_repro(
        benchmarks,
        benchmarks_dir=tmp_path / "benchmarks",
        pricing_dir=tmp_path / "pricing",
        results_dir=results_dir,
        regenerate=fake_regenerate,
        tmp_root=tmp_path,
        cleanup=True,
    )
    assert outcome.ok
    assert outcome.tmp_dir is None  # cleaned up
    # Canonical input dirs were forwarded unchanged.
    assert seen["benchmarks_dir"] == tmp_path / "benchmarks"
    assert seen["pricing_dir"] == tmp_path / "pricing"


def test_check_repro_mismatch_with_fake_regenerator(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    results_dir = tmp_path / "results"
    _seed_committed(results_dir, benchmarks, payload='{"ok":true}\n')

    def drifting_regenerate(bms, *, benchmarks_dir, pricing_dir, output_dir):
        _seed_committed(output_dir, bms, payload='{"ok":true}\n')
        _write(
            output_dir / "01-short-factual" / "inter_rater.json",
            '{"ok":false}\n',
        )

    outcome = cr.check_repro(
        benchmarks,
        benchmarks_dir=tmp_path / "benchmarks",
        pricing_dir=tmp_path / "pricing",
        results_dir=results_dir,
        regenerate=drifting_regenerate,
        tmp_root=tmp_path,
        cleanup=True,
    )
    assert not outcome.ok
    bad = [r for r in outcome.results if not r.ok]
    assert [r.artifact for r in bad] == ["inter_rater.json"]


def test_check_repro_preseeds_into_tmp(tmp_path: pathlib.Path) -> None:
    benchmarks = ("01-short-factual",)
    results_dir = tmp_path / "results"
    _seed_committed(results_dir, benchmarks, payload='{}\n')
    _write(
        results_dir / "01-short-factual" / cr.MANUAL_SPOT_CHECKS,
        '{"scores":[{"sample_id":"s","model":"m","effort":"low","repeat":0,"score":1}]}\n',
    )

    captured: dict[str, pathlib.Path] = {}

    def regen(bms, *, benchmarks_dir, pricing_dir, output_dir):
        captured["output_dir"] = output_dir
        # Manual scores must already be present at regenerate time.
        seeded_file = output_dir / "01-short-factual" / cr.MANUAL_SPOT_CHECKS
        assert seeded_file.is_file()
        _seed_committed(output_dir, bms, payload='{}\n')

    outcome = cr.check_repro(
        benchmarks,
        benchmarks_dir=tmp_path / "benchmarks",
        pricing_dir=tmp_path / "pricing",
        results_dir=results_dir,
        regenerate=regen,
        tmp_root=tmp_path,
        cleanup=False,
    )
    assert outcome.seeded_benchmarks == ["01-short-factual"]
    assert outcome.ok


def test_check_repro_manual_found_paths_root_invariant(
    tmp_path: pathlib.Path,
) -> None:
    """Pre-seeded manual scores must not break the byte-compare via tmp paths.

    Regression for T-064: the committed ``inter_rater.json`` is generated with
    ``--output-dir results/supplementary`` so it records the manual source as a
    repo-relative ``results/supplementary/<b>/manual_spot_checks.json``. The
    repro check pre-seeds that committed file into a *system tmp* output_dir and
    regenerates. The regenerated ``found_paths`` must record the same logical
    path (not an absolute ``/tmp/...`` path), so the byte comparison matches.

    The injected regenerator builds ``found_paths`` through the real
    :func:`inter_rater._load_manual_scores`, so this exercises the actual path
    normalization rather than a stand-in.
    """
    benchmark = "01-short-factual"
    # results_dir lives outside REPO_ROOT (a tmp tree), mirroring how the real
    # check_repro committed copy + tmp regeneration both sit outside the repo.
    results_dir = tmp_path / "results" / "supplementary"
    benchmarks_dir = tmp_path / "benchmarks"  # no committed manual inputs here
    manual_payload = json.dumps(
        [{"sample_id": "s1", "model": "gpt-5.2", "effort": "low",
          "repeat": 0, "reviewer_score": 2}]
    )
    _write(results_dir / benchmark / cr.MANUAL_SPOT_CHECKS, manual_payload)

    def make_inter_rater(output_dir: pathlib.Path) -> str:
        _, found, _ = ir._load_manual_scores(
            benchmark,
            benchmarks_dir=benchmarks_dir,
            output_dir=output_dir,
        )
        payload = {"manual_spot_checks": {"found_paths": sorted(found)}}
        return json.dumps(payload, indent=2, sort_keys=True) + "\n"

    # Committed artifacts: inter_rater.json generated as if output_dir == the
    # canonical results/supplementary root (the manual file lives under it).
    _write(results_dir / benchmark / "bootstrap_ci.json", "{}\n")
    _write(results_dir / benchmark / "cohens_d.json", "{}\n")
    _write(
        results_dir / benchmark / "inter_rater.json",
        make_inter_rater(results_dir),
    )

    def regen(bms, *, benchmarks_dir, pricing_dir, output_dir):
        # The pre-seed must have placed the manual file under the tmp output.
        seeded = output_dir / benchmark / cr.MANUAL_SPOT_CHECKS
        assert seeded.is_file()
        _write(output_dir / benchmark / "bootstrap_ci.json", "{}\n")
        _write(output_dir / benchmark / "cohens_d.json", "{}\n")
        _write(
            output_dir / benchmark / "inter_rater.json",
            make_inter_rater(output_dir),
        )

    outcome = cr.check_repro(
        (benchmark,),
        benchmarks_dir=benchmarks_dir,
        pricing_dir=tmp_path / "pricing",
        results_dir=results_dir,
        regenerate=regen,
        tmp_root=tmp_path,
        cleanup=True,
    )
    assert outcome.seeded_benchmarks == [benchmark]
    by_name = {r.artifact: r.status for r in outcome.results}
    assert by_name["inter_rater.json"] == "match"
    assert outcome.ok


# ----------------------------------------------------------------------------
# results-tree dirt guard
# ----------------------------------------------------------------------------


def test_results_porcelain_empty_outside_git(tmp_path: pathlib.Path) -> None:
    # A non-git directory yields an empty set (guard degrades to no-op).
    assert cr.results_porcelain(tmp_path) == set()
